# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d00b8ae56e8d20b1b5477af4640ba430f7a646b79365f7e3623d977267799089d624d9cd08dec173caade620ab392a0783e577d306864647c2af636df29614

test:
  secret_key_base: 19536664b8fde5ff538a41e0a25cbe13f8cc12d13aeae0fb8700b0635c44bbaf255ad2246f479b2536c50b1aa048d6f90263ae2cb02aa93bed7bff54ca7d0b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
